@'
apiVersion: v1
kind: Secret
metadata:
  name: catalog-db-secret
  namespace: eci
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpass123"
  MYSQL_USER: "catalog_user"
  MYSQL_PASSWORD: "S123pass"
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-app-secret
  namespace: eci
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-change-me"
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: eci
type: Opaque
stringData:
  SECRET_KEY: "flask-secret-change-me"
'@ | Out-File -FilePath .\1-secrets.yaml -Encoding utf8
