@'
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  namespace: eci
data:
  MYSQL_DATABASE: "catalog_db"
  MYSQL_HOST: "catalog-db"
  MYSQL_PORT: "3306"
  DJANGO_SETTINGS_MODULE: "catalog.settings"
  DJANGO_DEBUG: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
  namespace: eci
data:
  FLASK_ENV: "production"
  PORT: "8001"
'@ | Out-File -FilePath .\2-configmaps.yaml -Encoding utf8
